---
- name: Installer nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  tags: nginx

- name: Copier la configuration nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: nginx

- name: S'assurer que nginx est démarré
  service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx
