---
- name: Créer le répertoire /srv/app
  file:
    path: /srv/app
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  tags: app

- name: Copier le fichier index.php
  copy:
    src: index.php
    dest: /srv/app/index.php
    owner: www-data
    group: www-data
    mode: '0644'
  tags: app
